import type { MunicipioData } from "../types";

export const VALPARAISO: MunicipioData = {
  perfil: "urbano_medio",
  tipoPadrao: "Urbano",
  rodovias: [
    "SP-300 (Rodovia Marechal Rondon) — corta a cidade, km ~576",
    "Vicinais de ligação intermunicipal",
  ],
  comercio: [
    "Av. Nove de Julho (centro comercial)",
    "Rua Bartolomeu Bueno (zona comercial central)",
    "Centro (zona comercial de comércio geral)",
  ],
  bairros: [
    "Centro",
    "Jardim Primavera",
    "Jardim Flamboyant",
    "Jardim Morumbi",
    "Jardim Cristal",
    "Conj. Hab. Agrovila",
    "Conj. Hab. Rezende Nery",
    "Conj. Hab. Santana",
    "Conj. Hab. Valdivino de Souza Pacheco",
    "Conj. Hab. Valparaíso C",
    "Conj. Hab. Bela Vista",
    "Santa Casa",
    "Riviera",
    "Lambari",
    "Valdivino",
    "Ecoville",
    "Conjunto Habitacional Jonas Onofre",
    "Conj. Hab. Miguel Villar",
  ],
  pontosPE: [
    "Praça Oscar de Arruda (Praça Central)",
    "Banco do Brasil (Rua Quinze de Novembro, 70)",
    "Bradesco (Rua Quinze de Novembro, 41)",
    "Santander (Avenida Nove de Julho, 580)",
    "Caixa Econômica Federal (Rua Quinze de Novembro, s/n)",
    "Santa Casa de Misericórdia (Rua Bartolomeu Bueno, 241)",
    "Terminal Rodoviário (Avenida Nove de Julho)",
  ],
  pontosFisc: [
    "Saída do município sentido SP-300 (km 576)",
    "Acessos principais pela Vicinal Eugênio Salesse",
    "SP-300 km ~576 (Trecho crítico de acidentes - Infosiga)",
    "Complexo Penal - Entorno do CPP Valparaíso (Estrada VPS 012)",
    "Rotas de fuga - Saídas para SP-300 (Prevenção a roubo a bancos de madrugada)",
  ],
  rural: [
    "AISP I rural",
    "AISP II rural",
    "AISP III rural",
    "Estrada da Usina da Mata",
    "Madalena",
    "Divisa",
    "Vila Messias",
    "Aguapeí",
    "Nova Serrinha",
    "Sergipe",
    "Vicinal VPS 012 — Acesso ao CPP Valparaíso",
  ],
  eventos: [
    { nome: "Safra de cana-de-açúcar", mes: 4 },
    { nome: "Safra de cana-de-açúcar", mes: 5 },
    { nome: "Safra de cana-de-açúcar", mes: 6 },
    { nome: "Safra de cana-de-açúcar", mes: 7 },
    { nome: "Safra de cana-de-açúcar", mes: 8 },
    { nome: "Safra de cana-de-açúcar", mes: 9 },
    { nome: "Safra de cana-de-açúcar", mes: 10 },
    { nome: "Safra de cana-de-açúcar", mes: 11 },
  ],
  obs: "Sede do pelotão PM (~24.241 hab. Censo 2022); o motor não deve gerar DESL aqui; possui parque industrial e complexo penal (CPP Valparaíso) nos acessos.",
};
