import type { DadosPPI } from "./types-ppi";
import type { Municipio } from "../types";

export const PPI_5CIA: Record<Municipio, DadosPPI> = {
  Guararapes: {
    aisp: ["AISP 1 (Setor Urbano)", "AISP 2 (Setor Rural / Ribeiro do Vale)"],
    hotspots: [
      {
        local: "Zona Comercial da Av. Rio Branco",
        endereco: "Av. Rio Branco, Centro, Guararapes - SP",
        bairro: "Centro",
        crimePrincipal: "Furto",
        periodosCriticos: ["manha", "tarde"],
        horaInicioCritico: 9,
        horaFimCritico: 18,
        diasCriticos: ["quinta", "sexta", "sabado"],
        frequenciaAnual: 45,
        modalidadesRecomendadas: ["POST", "PE"],
        risco: "Médio",
        fonte: "comando_5cia",
        confianca: "estimado",
        lat: -21.2622,
        lng: -50.6421,
      },
      {
        local: "Área Industrial - Entorno da Usina Unialco",
        endereco: "Estrada da Usina Unialco, Guararapes - SP",
        bairro: "Zona Rural",
        crimePrincipal: "Furto de fios e defensivos agrícolas",
        periodosCriticos: ["noite", "madrugada"],
        horaInicioCritico: 22,
        horaFimCritico: 6,
        diasCriticos: ["quinta", "sexta", "sabado", "domingo"],
        frequenciaAnual: 12,
        modalidadesRecomendadas: ["RURAL"],
        risco: "Médio",
        fonte: "comando_5cia",
        confianca: "estimado",
        lat: -21.2185,
        lng: -50.695,
      },
    ],
    escolas: [
      {
        nome: "EE Prof. Aimone Sala",
        endereco: "Av. Marechal Floriano, 905, Centro, Guararapes - SP",
        bairro: "Centro",
        tipo: "Estadual",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Estadual",
        etapas: ["Fundamental", "Medio"],
        lat: -21.2635,
        lng: -50.6425,
      },
      {
        nome: "EE João Arruda Brasil",
        endereco: "Rua Prudente de Morais, 951, Centro, Guararapes - SP",
        bairro: "Centro",
        tipo: "Estadual",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Estadual",
        etapas: ["Fundamental", "Medio", "EJA"],
        lat: -21.2615,
        lng: -50.641,
      },
      {
        nome: "EE Prof. Waldemar Queiroz",
        endereco: "Rua Adelmo Caleffi, 120, Jardim Aeroporto, Guararapes - SP",
        bairro: "Jardim Aeroporto",
        tipo: "Estadual",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Estadual",
        etapas: ["Fundamental", "Medio"],
        lat: -21.255,
        lng: -50.635,
      },
      {
        nome: "EMEB Dr. Antonio Pinto de Oliveira",
        endereco: "Rua Aymorés, 350, Centro, Guararapes - SP",
        bairro: "Centro",
        tipo: "Municipal",
        turnoEntrada: "07:00",
        turnoSaida: "12:00",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:00",
        dependencia: "Municipal",
        etapas: ["Fundamental", "Pre-escola"],
        lat: -21.2648,
        lng: -50.6405,
      },
      {
        nome: "EMEB Professora Brigida Cagnin Zancaner",
        endereco: "Rua General Osório, 1420, Bairro Industrial, Guararapes - SP",
        bairro: "Bairro Industrial",
        tipo: "Municipal",
        turnoEntrada: "07:30",
        turnoSaida: "16:30",
        turnoEntradaTarde: null,
        turnoSaidaTarde: null,
        dependencia: "Municipal",
        etapas: ["Pre-escola", "Creche"],
        lat: -21.2592,
        lng: -50.6492,
      },
      {
        nome: "EMEB Professor Francisco de Almeida Ribeiro",
        endereco: "Rua Prudente de Morais, 137, Centro, Guararapes - SP",
        bairro: "Centro",
        tipo: "Municipal",
        turnoEntrada: "07:00",
        turnoSaida: "12:00",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:00",
        dependencia: "Municipal",
        etapas: ["Fundamental", "Pre-escola"],
        lat: -21.2625,
        lng: -50.6438,
      },
      {
        nome: "EMEB Professora Ivete Abdo Theodoro de Oliveira",
        endereco: "Rua Aymorés, 1500, Jardim Continental, Guararapes - SP",
        bairro: "Jardim Continental",
        tipo: "Municipal",
        turnoEntrada: "07:00",
        turnoSaida: "12:00",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:00",
        dependencia: "Municipal",
        etapas: ["Fundamental", "Pre-escola"],
        lat: -21.2531,
        lng: -50.6515,
      },
    ],
    infraestruturaCritica: {
      delegacia: {
        nome: "Delegacia de Polícia Civil de Guararapes",
        endereco: "Rua Prudente de Morais, 385, Centro, Guararapes - SP",
        telefone: "(18) 3606-4999",
      },
      upa: {
        nome: "Pronto Socorro - Santa Casa de Misericórdia de Guararapes",
        endereco: "Avenida Marechal Floriano, 1602, Centro, Guararapes - SP",
        telefone: "(18) 3406-9000",
      },
      bombeiros: null,
    },
    policiaComunitaria: {
      programas: [
        {
          nome: "PROERD",
          ativo: true,
          fonte: "PMESP",
          fonteUrl: "https://www.policiamilitar.sp.gov.br/portal/proerd.html",
        },
        {
          nome: "Patrulha Maria da Penha",
          ativo: null,
          fonte: "comando_5cia (a validar pelo comando)",
          fonteUrl: null,
        },
        {
          nome: "Vizinhança Solidária",
          ativo: null,
          fonte: "comando_5cia (a validar pelo comando)",
          fonteUrl: null,
        },
      ],
    },
    perfilCriminal: {
      anoMovel: "2025-01 a 2025-12",
      homicidioDoloso: 3,
      rouboOutros: 13,
      furtoOutros: 184,
      furtoVeiculo: 7,
      rouboVeiculo: 0,
      violenciaDomestica: null,
      lesaoCorporalDolosa: 85,
      trafico: 28,
      perturbacaoSossego: null,
      danoVandalismo: null,
      embriaguezVolante: null,
      indicadorDominante: "furto",
      tendencia: "queda",
      confianca: "oficial",
      fonte: "SSP-SP Ocorrências Anuais, Mensais & Produtividade (Guararapes)",
      fonteUrl: "file:///G:/Meu Drive/Arquivos Josemar/Projetos não vercionados/5 Cia/Roteiro de policiamento/dados criminais/OcorrenciaAnual-Guararapes_20260616_124113.xlsx",
    },
    transito: {
      periodoReferencia: "2021-06 a 2026-06",
      totalComVitima: 388,
      totalSemVitima: 416,
      totalFatais: 18,
      veiculoMaisEnvolvido: "motocicleta",
      tiposViaCriticos: ["SP-300 km 550-555", "Av. Rio Branco", "SP-473"],
      horariosCriticos: [17, 18, 19],
      diasCriticos: ["sexta", "sabado"],
      observacao: "Alta ocorrência de sinistros com motocicletas na Av. Rio Branco e colisões traseiras na SP-300.",
      fonte: "Infosiga-SP Painel de Sinistros (Guararapes)",
      confianca: "oficial",
      fonteUrl: "file:///G:/Meu Drive/Arquivos Josemar/Projetos não vercionados/5 Cia/Roteiro de policiamento/sinistros/Painel_de_Sinistros guararapes.pdf",
    },
    frota: {
      total: 26933,
      automoveis: 12769,
      motocicletas: 5191,
      caminhoes: 721,
      percentualMotos: 0.1927,
      dataReferencia: "2026-05",
      fonte: "Senatran - Frota por Município (Maio/2026)",
      confianca: "oficial",
      fonteUrl: "file:///G:/Meu Drive/Arquivos Josemar/Projetos não vercionados/5 Cia/Roteiro de policiamento/Frota_por_municipio_e_tipo_Maio_2026.xlsx",
    },
    saude: [
      {
        nome: "Pronto Socorro - Santa Casa de Misericórdia de Guararapes",
        tipo: "Hospital",
        endereco: "Avenida Marechal Floriano, 1602, Centro, Guararapes - SP",
        telefone: "(18) 3406-9000",
        funciona24h: true,
        fonte: "CNES/DATASUS",
        lat: -21.258,
        lng: -50.6465,
      },
    ],
    instituicoesFinanceiras: [
      {
        tipo: "Agencia",
        nome: "Banco do Brasil - Agência Guararapes",
        banco: "Banco do Brasil",
        endereco: "Praça Nossa Senhora da Conceição, 308 - Centro, Guararapes - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
        lat: -21.2618,
        lng: -50.6425,
      },
      {
        tipo: "Agencia",
        nome: "Bradesco - Agência Guararapes",
        banco: "Bradesco",
        endereco: "Rua Marechal Deodoro, 1021 - Centro, Guararapes - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
        lat: -21.262,
        lng: -50.6429,
      },
      {
        tipo: "Agencia",
        nome: "Caixa Econômica Federal - Agência Guararapes",
        banco: "Caixa",
        endereco: "Avenida Marechal Floriano, 675 - Centro, Guararapes - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
        lat: -21.2614,
        lng: -50.6432,
      },
      {
        tipo: "Loterica",
        nome: "Lotérica Guararapes",
        banco: "Caixa",
        endereco: "Rua Prudente de Morais, s/n - Centro, Guararapes - SP",
        alvoExplosaoCaixa: false,
        fonte: "Caixa",
        lat: -21.2612,
        lng: -50.6438,
      },
    ],
    ruralDetalhe: {
      totalPropriedades: 512,
      clustersAcesso: [
        "Estrada Vicinal GRP-010",
        "Estrada da Usina Unialco",
        "Estrada da Fazenda JBS",
      ],
      producaoPrincipal: ["cana-de-açúcar", "pasto/pecuária de corte"],
      alvosFurtoRural: [
        "defensivos agrícolas",
        "fios de cobre",
        "combustível",
        "implementos",
      ],
      fonte: "IBGE Censo Agro / CAR",
    },
    pontosAglomeracao: [
      {
        nome: "Feira Livre de Guararapes",
        tipo: "FeiraLivre",
        endereco: "Praça Nossa Senhora da Conceição, Centro, Guararapes - SP",
        diasHorarios: "Quarta e sábado 06:00-13:00",
        fonte: "Prefeitura de Guararapes",
        lat: -21.2618,
        lng: -50.6425,
      },
    ],
    pontosEconomicos: [
      {
        nome: "Supermercado Big Mart - Loja Baguassu",
        tipo: "Supermercado",
        endereco: "Rua Baguassu, 1205, Jardim Acapulco, Guararapes - SP",
        bairro: "Jardim Acapulco",
        lat: -21.2536,
        lng: -50.6415,
        fonte: "Rede Big Mart",
        fonteUrl: "https://www.redebigmart.com.br",
      },
      {
        nome: "Sakashita Supermercados - Loja 08",
        tipo: "Supermercado",
        endereco: "Avenida Rio Branco, 841, Centro, Guararapes - SP",
        bairro: "Centro",
        lat: -21.2619,
        lng: -50.6427,
        fonte: "Sakashita Supermercados",
        fonteUrl: "https://www.sakashita.com.br",
      },
      {
        nome: "Auto Posto Guararapes (Shell)",
        tipo: "Posto",
        endereco: "Avenida Rio Branco, 1726, Centro, Guararapes - SP",
        bairro: "Centro",
        lat: -21.2582,
        lng: -50.6385,
        fonte: "ANP",
        fonteUrl: "https://www.gov.br/anp",
      },
    ],
    entidadesSociais: [
      {
        nome: "CRAS - Centro de Referência de Assistência Social de Guararapes",
        tipo: "CRAS",
        endereco: "Rua Duque de Caxias, 1165, Jardim Dom Luiz Orione I, Guararapes - SP",
        bairro: "Jardim Dom Luiz Orione",
        lat: -21.2655,
        lng: -50.6358,
        publicoAlvo: "Famílias e indivíduos em situação de vulnerabilidade social",
        relevanciaPrevencao: "Prevenção primária por meio de assistência a famílias vulneráveis, reduzindo fatores de risco social",
        fonte: "Prefeitura Municipal de Guararapes",
        fonteUrl: "https://www.guararapes.sp.gov.br",
      },
    ],
    unidadesPrisionais: null,
    metadata: {
      versao: "3.3",
      dataLevantamento: "2026-06-16",
      responsavel: "Agente de Inteligência de Segurança Pública",
      fontes: [
        "Prefeitura Municipal de Guararapes",
        "Rede Big Mart",
        "Sakashita Supermercados",
        "ANP (Postos)",
        "OpenStreetMap/Nominatim Geocoding",
      ],
      statusValidacao: "parcial",
      camposNaoEncontrados: [
        "DadosPPI.Guararapes.perfilCriminal.violenciaDomestica",
        "DadosPPI.Guararapes.perfilCriminal.perturbacaoSossego",
        "DadosPPI.Guararapes.perfilCriminal.danoVandalismo",
        "DadosPPI.Guararapes.perfilCriminal.embriaguezVolante",
      ],
    },
  },
  Valparaíso: {
    aisp: [
      "AISP I (Setor Rural Norte)",
      "AISP II (Setor Rural Oeste)",
      "AISP III (Setor Rural Sul)",
      "AISP IV (Setor Urbano / Comercial)",
    ],
    hotspots: [
      {
        local: "Zona Comercial da Av. Nove de Julho",
        endereco: "Av. Nove de Julho, Centro, Valparaíso - SP",
        bairro: "Centro",
        crimePrincipal: "Furto",
        periodosCriticos: ["manha", "tarde"],
        horaInicioCritico: 9,
        horaFimCritico: 19,
        diasCriticos: ["quinta", "sexta", "sabado"],
        frequenciaAnual: 50,
        modalidadesRecomendadas: ["POST", "PE"],
        risco: "Médio",
        fonte: "comando_5cia",
        confianca: "estimado",
        lat: -21.2295,
        lng: -50.8681,
      },
    ],
    escolas: [
      {
        nome: "EE Vicente Barbosa",
        endereco: "Rua Agostinho Barbosa, 335, Centro, Valparaíso - SP",
        bairro: "Centro",
        tipo: "Estadual",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Estadual",
        etapas: ["Fundamental", "Medio"],
        lat: -21.2285,
        lng: -50.869,
      },
      {
        nome: "EE Prof. David Golias",
        endereco: "Rua Gaspar Vaz, 700, Conj. Hab. Miguel Villar, Valparaíso - SP",
        bairro: "Conj. Hab. Miguel Villar",
        tipo: "Estadual",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Estadual",
        etapas: ["Fundamental", "Medio"],
        lat: -21.223,
        lng: -50.861,
      },
      {
        nome: "EMEF Prof. Persio Scatena Garcia",
        endereco: "Rua Bartolomeu Bueno, 878, Centro, Valparaíso - SP",
        bairro: "Centro",
        tipo: "Municipal",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Municipal",
        etapas: ["Fundamental"],
        lat: -21.2268,
        lng: -50.8655,
      },
      {
        nome: "EMEF José de Castro",
        endereco: "Rua Eduardo Geralde, 289, Centro, Valparaíso - SP",
        bairro: "Centro",
        tipo: "Municipal",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Municipal",
        etapas: ["Fundamental"],
        lat: -21.2245,
        lng: -50.8665,
      },
      {
        nome: "EMEF Djanira dos Santos Benetti",
        endereco: "Rua Eurípides Leite Bastos, 116, Valparaíso - SP",
        bairro: "Centro",
        tipo: "Municipal",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Municipal",
        etapas: ["Fundamental"],
        lat: -21.2215,
        lng: -50.8695,
      },
    ],
    infraestruturaCritica: {
      delegacia: {
        nome: "Delegacia de Polícia Civil de Valparaíso",
        endereco: "Rua Juca de Castro, 297, Valparaíso - SP",
        telefone: "(18) 3401-1246",
      },
      upa: {
        nome: "Santa Casa de Misericórdia de Valparaíso",
        endereco: "Rua Bartolomeu Bueno, 241, Centro, Valparaíso - SP",
        telefone: "(18) 3401-7171",
      },
      bombeiros: null,
    },
    policiaComunitaria: {
      programas: [
        {
          nome: "PROERD",
          ativo: true,
          fonte: "PMESP",
          fonteUrl: "https://www.policiamilitar.sp.gov.br/portal/proerd.html",
        },
        {
          nome: "Policiamento Escolar",
          ativo: true,
          fonte: "comando_5cia",
          fonteUrl: "https://www.policiamilitar.sp.gov.br",
        },
        {
          nome: "Patrulha Maria da Penha",
          ativo: null,
          fonte: "comando_5cia (a validar pelo comando)",
          fonteUrl: null,
        },
      ],
    },
    perfilCriminal: {
      anoMovel: "2025-01 a 2025-12",
      homicidioDoloso: 4,
      rouboOutros: 6,
      furtoOutros: 97,
      furtoVeiculo: 2,
      rouboVeiculo: 0,
      violenciaDomestica: null,
      lesaoCorporalDolosa: 81,
      trafico: 50,
      perturbacaoSossego: null,
      danoVandalismo: null,
      embriaguezVolante: null,
      indicadorDominante: "furto",
      tendencia: "queda",
      confianca: "oficial",
      fonte: "SSP-SP Ocorrências Anuais, Mensais e Produtividade (Valparaíso)",
      fonteUrl: "file:///G:/Meu Drive/Arquivos Josemar/Projetos não vercionados/5 Cia/Roteiro de policiamento/dados criminais/OcorrenciaAnual-Valparaíso_20260616_124135.xlsx",
    },
    transito: {
      periodoReferencia: "2021-06 a 2026-06",
      totalComVitima: 203,
      totalSemVitima: 183,
      totalFatais: 6,
      veiculoMaisEnvolvido: "motocicleta",
      tiposViaCriticos: [
        "SP-300 km 573-578",
        "Av. Nove de Julho",
        "Vicinal Eugênio Salesse",
      ],
      horariosCriticos: [18, 19, 20],
      diasCriticos: ["sexta", "sabado"],
      observacao: "Foco de colisões e atropelamentos no trecho urbano da SP-300 no final da tarde.",
      fonte: "Infosiga-SP Painel de Sinistros (Valparaíso)",
      confianca: "oficial",
      fonteUrl: "file:///G:/Meu Drive/Arquivos Josemar/Projetos não vercionados/5 Cia/Roteiro de policiamento/sinistros/Painel_de_Sinistros valparaiso.pdf",
    },
    frota: {
      total: 15075,
      automoveis: 8512,
      motocicletas: 2223,
      caminhoes: 494,
      percentualMotos: 0.1475,
      dataReferencia: "2026-05",
      fonte: "Senatran - Frota por Município (Maio/2026)",
      confianca: "oficial",
      fonteUrl: "file:///G:/Meu Drive/Arquivos Josemar/Projetos não vercionados/5 Cia/Roteiro de policiamento/Frota_por_municipio_e_tipo_Maio_2026.xlsx",
    },
    saude: [
      {
        nome: "Santa Casa de Misericórdia de Valparaíso",
        tipo: "SantaCasa",
        endereco: "Rua Bartolomeu Bueno, 241, Centro, Valparaíso - SP",
        telefone: "(18) 3401-7171",
        funciona24h: true,
        fonte: "CNES/DATASUS",
        lat: -21.2272,
        lng: -50.866,
      },
    ],
    instituicoesFinanceiras: [
      {
        tipo: "Agencia",
        nome: "Banco do Brasil - Agência Valparaíso",
        banco: "Banco do Brasil",
        endereco: "Rua Quinze de Novembro, 70 - Centro, Valparaíso - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
        lat: -21.2278,
        lng: -50.8685,
      },
      {
        tipo: "Agencia",
        nome: "Bradesco - Agência Valparaíso",
        banco: "Bradesco",
        endereco: "Rua Quinze de Novembro, 41 - Centro, Valparaíso - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
        lat: -21.2281,
        lng: -50.8687,
      },
      {
        tipo: "Agencia",
        nome: "Santander - Agência Valparaíso",
        banco: "Santander",
        endereco: "Avenida Nove de Julho, 580 - Centro, Valparaíso - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
        lat: -21.2291,
        lng: -50.8678,
      },
      {
        tipo: "Agencia",
        nome: "Caixa Econômica Federal - Agência Valparaíso",
        banco: "Caixa",
        endereco: "Rua Quinze de Novembro, s/n - Centro, Valparaíso - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
        lat: -21.2275,
        lng: -50.8688,
      },
      {
        tipo: "Loterica",
        nome: "Lotérica Valparaíso",
        banco: "Caixa",
        endereco: "Rua Quinze de Novembro, Centro, Valparaíso - SP",
        alvoExplosaoCaixa: false,
        fonte: "Caixa",
        lat: -21.2285,
        lng: -50.869,
      },
    ],
    ruralDetalhe: {
      totalPropriedades: 398,
      clustersAcesso: ["Estrada da Usina da Mata", "Vicinais de ligação rural"],
      producaoPrincipal: ["cana-de-açúcar", "pasto"],
      alvosFurtoRural: ["defensivos agrícolas", "fios de cobre", "combustível"],
      fonte: "IBGE Censo Agro / CAR",
    },
    pontosAglomeracao: [
      {
        nome: "Terminal Rodoviário de Valparaíso",
        tipo: "Terminal",
        endereco: "Avenida Nove de Julho, Centro, Valparaíso - SP",
        diasHorarios: "Diário 24h",
        fonte: "Prefeitura de Valparaíso",
        lat: -21.2298,
        lng: -50.8672,
      },
    ],
    pontosEconomicos: [
      {
        nome: "Empório Redepas - Valparaíso",
        tipo: "Supermercado",
        endereco: "Rua Eduardo Geraldi, 125, Centro, Valparaíso - SP",
        bairro: "Centro",
        lat: -21.2248,
        lng: -50.8662,
        fonte: "Rede Redepas",
        fonteUrl: "https://www.redepas.com.br",
      },
      {
        nome: "Auto Posto Bremen (Shell)",
        tipo: "Posto",
        endereco: "Rua Nelson Salesse, 15, Parque Micro e Pequena, Valparaíso - SP",
        bairro: "Parque Micro e Pequena",
        lat: -21.2212,
        lng: -50.8705,
        fonte: "ANP",
        fonteUrl: "https://www.gov.br/anp",
      },
      {
        nome: "Auto Posto Noroeste (Petrobras)",
        tipo: "Posto",
        endereco: "Rua Francisco de Carvalho, 588, Centro, Valparaíso - SP",
        bairro: "Centro",
        lat: -21.2265,
        lng: -50.8692,
        fonte: "ANP",
        fonteUrl: "https://www.gov.br/anp",
      },
    ],
    entidadesSociais: [
      {
        nome: "CRAS - Centro de Referência de Assistência Social de Valparaíso",
        tipo: "CRAS",
        endereco: "Rua Álvaro de Paula, 55, Bairro Asa Branca, Valparaíso - SP",
        bairro: "Asa Branca",
        lat: -21.2205,
        lng: -50.8621,
        publicoAlvo: "Famílias e indivíduos em vulnerabilidade social e beneficiários do CadÚnico",
        relevanciaPrevencao: "Prevenção primária por meio do fortalecimento de vínculos familiares e comunitários",
        fonte: "Prefeitura Municipal de Valparaíso",
        fonteUrl: "https://www.valparaiso.sp.gov.br",
      },
    ],
    unidadesPrisionais: [
      {
        nome: "Centro de Progressão Penitenciária de Valparaíso (CPP)",
        tipo: "Presídio Semiaberto",
        endereco: "Estrada Municipal VPS 012/VPS 351, Km 02 - Bairro Valdevino Souza Pacheco, Valparaíso/SP",
        lat: -21.205,
        lng: -50.885,
      },
      {
        nome: "Penitenciária de Valparaíso",
        tipo: "Presídio Regime Fechado",
        endereco: "Estrada Municipal VPS 012/VPS 351, Km 02 - Bairro Valdevino Souza Pacheco, Valparaíso/SP",
        lat: -21.2045,
        lng: -50.8845,
      },
    ],
    metadata: {
      versao: "3.3",
      dataLevantamento: "2026-06-16",
      responsavel: "Agente de Inteligência de Segurança Pública",
      fontes: [
        "Prefeitura Municipal de Valparaíso",
        "Rede Redepas",
        "ANP (Postos)",
        "OpenStreetMap/Nominatim Geocoding",
      ],
      statusValidacao: "parcial",
      camposNaoEncontrados: [
        "DadosPPI.Valparaíso.perfilCriminal.violenciaDomestica",
        "DadosPPI.Valparaíso.perfilCriminal.perturbacaoSossego",
        "DadosPPI.Valparaíso.perfilCriminal.danoVandalismo",
        "DadosPPI.Valparaíso.perfilCriminal.embriaguezVolante",
      ],
    },
  },
  Rubiácea: {
    aisp: ["AISP 1 (Município de Rubiácea)"],
    hotspots: [
      {
        local: "Trevo de Acesso à SP-300 / Praça de Pedágio",
        endereco: "SP-300 Rodovia Marechal Rondon, km 562, Rubiácea - SP",
        bairro: "Zona Rural",
        crimePrincipal: "Evasão de divisas / Roubo / Furto de carga",
        periodosCriticos: ["noite", "madrugada"],
        horaInicioCritico: 21,
        horaFimCritico: 5,
        diasCriticos: ["terça", "quarta", "quinta", "sexta"],
        frequenciaAnual: 8,
        modalidadesRecomendadas: ["FISC"],
        risco: "Baixo",
        fonte: "comando_5cia",
        confianca: "estimado",
        lat: -21.2912,
        lng: -50.755,
      },
    ],
    escolas: [
      {
        nome: "EE Coronel Francisco Prudente Correa",
        endereco: "Rua Dona Angelina de Lima Correa, 168, Centro, Rubiácea - SP",
        bairro: "Centro",
        tipo: "Estadual",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Estadual",
        etapas: ["Fundamental", "Medio", "EJA"],
        lat: -21.2995,
        lng: -50.7275,
      },
      {
        nome: "EMEF Professor Luciano Tavares de Moraes",
        endereco: "Rua Ozório Brasileiro da Silva, 25, Centro, Rubiácea - SP",
        bairro: "Centro",
        tipo: "Municipal",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Municipal",
        etapas: ["Fundamental"],
        lat: -21.2985,
        lng: -50.7285,
      },
      {
        nome: "EMEF Renato de Freitas",
        endereco: "Rua São João, 185, Caramuru, Rubiácea - SP",
        bairro: "Zona Rural",
        tipo: "Municipal",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Municipal",
        etapas: ["Fundamental"],
        lat: -21.321,
        lng: -50.7112,
      },
    ],
    infraestruturaCritica: {
      delegacia: {
        nome: "Delegacia de Polícia Civil de Rubiácea",
        endereco: "Rua Cel. Francisco Prudente Corrêa, 445, Centro, Rubiácea - SP",
        telefone: "(18) 3697-1119",
      },
      upa: {
        nome: "UBS III de Rubiácea",
        endereco: "Rua Francisco de Paula Leite Nogueira, 208, Centro, Rubiácea - SP",
        telefone: "(18) 3697-1128",
      },
      bombeiros: null,
    },
    policiaComunitaria: {
      programas: [
        {
          nome: "PROERD",
          ativo: null,
          fonte: "comando_5cia (a validar pelo comando)",
          fonteUrl: null,
        },
        {
          nome: "Ronda Rural",
          ativo: true,
          fonte: "comando_5cia",
          fonteUrl: "https://www.policiamilitar.sp.gov.br",
        },
      ],
    },
    perfilCriminal: {
      anoMovel: "2025-01 a 2025-12",
      homicidioDoloso: 0,
      rouboOutros: 0,
      furtoOutros: 9,
      furtoVeiculo: 0,
      rouboVeiculo: 0,
      violenciaDomestica: null,
      lesaoCorporalDolosa: 14,
      trafico: 1,
      perturbacaoSossego: null,
      danoVandalismo: null,
      embriaguezVolante: null,
      indicadorDominante: "furto",
      tendencia: "alta",
      confianca: "oficial",
      fonte: "SSP-SP Ocorrências Anuais, Mensais e Produtividade (Rubiácea)",
      fonteUrl: "file:///G:/Meu Drive/Arquivos Josemar/Projetos não vercionados/5 Cia/Roteiro de policiamento/dados criminais/OcorrenciaAnual-Rubiácea_20260616_124124.xlsx",
    },
    transito: {
      periodoReferencia: "2021-06 a 2026-06",
      totalComVitima: 7,
      totalSemVitima: 18,
      totalFatais: 0,
      veiculoMaisEnvolvido: "automovel",
      tiposViaCriticos: ["SP-300 km 560-564", "Vicinal Geraldo Stringhetta"],
      horariosCriticos: [7, 18],
      diasCriticos: ["domingo"],
      observacao: "Sinistros concentrados na praça de pedágio e na vicinal de acesso ao bairro Caramuru.",
      fonte: "Infosiga-SP Painel de Sinistros (Rubiácea)",
      confianca: "oficial",
      fonteUrl: "file:///G:/Meu Drive/Arquivos Josemar/Projetos não vercionados/5 Cia/Roteiro de policiamento/sinistros/Painel_de_Sinistros rubiacea.pdf",
    },
    frota: {
      total: 1675,
      automoveis: 998,
      motocicletas: 284,
      caminhoes: 39,
      percentualMotos: 0.1696,
      dataReferencia: "2026-05",
      fonte: "Senatran - Frota por Município (Maio/2026)",
      confianca: "oficial",
      fonteUrl: "file:///G:/Meu Drive/Arquivos Josemar/Projetos não vercionados/5 Cia/Roteiro de policiamento/Frota_por_municipio_e_tipo_Maio_2026.xlsx",
    },
    saude: [
      {
        nome: "UBS III de Rubiácea",
        tipo: "UBS",
        endereco: "Rua Francisco de Paula Leite Nogueira, 208 - Centro, Rubiácea - SP",
        telefone: "(18) 3697-1128",
        funciona24h: false,
        fonte: "CNES/DATASUS",
        lat: -21.3005,
        lng: -50.7265,
      },
    ],
    instituicoesFinanceiras: [
      {
        tipo: "Agencia",
        nome: "Banco do Brasil - Agência Rubiácea",
        banco: "Banco do Brasil",
        endereco: "Avenida Min. Konder, 107 - Centro, Rubiácea - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
        lat: -21.2982,
        lng: -50.7288,
      },
    ],
    ruralDetalhe: {
      totalPropriedades: 185,
      clustersAcesso: ["Vicinal Geraldo Stringhetta (Rubiácea a Caramuru)"],
      producaoPrincipal: ["cana-de-açúcar", "pasto"],
      alvosFurtoRural: ["defensivos agrícolas", "fios de cobre", "combustível"],
      fonte: "IBGE Censo Agro / CAR",
    },
    pontosAglomeracao: [],
    pontosEconomicos: [
      {
        nome: "Supermercado Maria Elena Sanita Bonfietti",
        tipo: "Supermercado",
        endereco: "Rua Sir Alexander Fleming, s/n, Centro, Rubiácea - SP",
        bairro: "Centro",
        lat: -21.2988,
        lng: -50.7282,
        fonte: "Prefeitura de Rubiácea / Junta Comercial",
        fonteUrl: "https://www.rubiacea.sp.gov.br",
      },
    ],
    entidadesSociais: [
      {
        nome: "CRAS - Centro de Referência de Assistência Social de Rubiácea",
        tipo: "CRAS",
        endereco: "Rua Praça do Café, 101, Centro, Rubiácea - SP",
        bairro: "Centro",
        lat: -21.2991,
        lng: -50.7271,
        publicoAlvo: "Famílias de baixa renda e pequenos produtores rurais vulneráveis",
        relevanciaPrevencao: "Prevenção secundária e inclusão produtiva para mitigação de vulnerabilidade rural",
        fonte: "Prefeitura Municipal de Rubiácea",
        fonteUrl: "https://www.rubiacea.sp.gov.br",
      },
    ],
    unidadesPrisionais: null,
    metadata: {
      versao: "3.3",
      dataLevantamento: "2026-06-16",
      responsavel: "Agente de Inteligência de Segurança Pública",
      fontes: [
        "Prefeitura Municipal de Rubiácea",
        "Junta Comercial (JUCESP)",
        "OpenStreetMap/Nominatim Geocoding",
      ],
      statusValidacao: "parcial",
      camposNaoEncontrados: [
        "DadosPPI.Rubiácea.perfilCriminal.violenciaDomestica",
        "DadosPPI.Rubiácea.perfilCriminal.perturbacaoSossego",
        "DadosPPI.Rubiácea.perfilCriminal.danoVandalismo",
        "DadosPPI.Rubiácea.perfilCriminal.embriaguezVolante",
      ],
    },
  },
  "Bento de Abreu": {
    aisp: ["AISP 1 (Município de Bento de Abreu)"],
    hotspots: [
      {
        local: "Trevo de Bento de Abreu (SP-300 / SP-568)",
        endereco: "Trevo de Bento de Abreu, Bento de Abreu - SP",
        bairro: "Zona Rural",
        crimePrincipal: "Tráfico de drogas / Furto de veículos",
        periodosCriticos: ["noite", "madrugada"],
        horaInicioCritico: 18,
        horaFimCritico: 4,
        diasCriticos: ["sexta", "sabado", "domingo"],
        frequenciaAnual: 10,
        modalidadesRecomendadas: ["FISC"],
        risco: "Baixo",
        fonte: "comando_5cia",
        confianca: "estimado",
        lat: -21.2652,
        lng: -50.8285,
      },
    ],
    escolas: [
      {
        nome: "EE Prof. Olímpio Camargo",
        endereco: "Rua 27 de Março, 640, Centro, Bento de Abreu - SP",
        bairro: "Centro",
        tipo: "Estadual",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Estadual",
        etapas: ["Fundamental", "Medio", "EJA"],
        lat: -21.2695,
        lng: -50.8125,
      },
      {
        nome: "EMEF Prof. Dorival Reis Camargo Barrionuevo Sanchez",
        endereco: "Rua Hugo Scatena, 687, Centro, Bento de Abreu - SP",
        bairro: "Centro",
        tipo: "Municipal",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Municipal",
        etapas: ["Fundamental"],
        lat: -21.2678,
        lng: -50.8112,
      },
    ],
    infraestruturaCritica: {
      delegacia: {
        nome: "Delegacia de Polícia Civil de Bento de Abreu",
        endereco: "Rua João Belmiro de Brito, s/nº, Centro, Bento de Abreu - SP",
        telefone: "(18) 3601-1221",
      },
      upa: {
        nome: "UBS Dr. José Rosseto",
        endereco: "Rua José Rosseto, 58, Centro, Bento de Abreu - SP",
        telefone: "(18) 3601-1321",
      },
      bombeiros: null,
    },
    policiaComunitaria: {
      programas: [
        {
          nome: "PROERD",
          ativo: null,
          fonte: "comando_5cia (a validar pelo comando)",
          fonteUrl: null,
        },
        {
          nome: "Ronda Rural",
          ativo: true,
          fonte: "comando_5cia",
          fonteUrl: "https://www.policiamilitar.sp.gov.br",
        },
      ],
    },
    perfilCriminal: {
      anoMovel: "2025-01 a 2025-12",
      homicidioDoloso: 0,
      rouboOutros: 0,
      furtoOutros: 17,
      furtoVeiculo: 0,
      rouboVeiculo: 0,
      violenciaDomestica: null,
      lesaoCorporalDolosa: 6,
      trafico: 1,
      perturbacaoSossego: null,
      danoVandalismo: null,
      embriaguezVolante: null,
      indicadorDominante: "furto",
      tendencia: "alta",
      confianca: "oficial",
      fonte: "SSP-SP Ocorrências Anuais, Mensais e Produtividade (Bento de Abreu)",
      fonteUrl: "file:///G:/Meu Drive/Arquivos Josemar/Projetos não vercionados/5 Cia/Roteiro de policiamento/dados criminais/OcorrenciaAnual-Bento de Abreu_20260616_124100.xlsx",
    },
    transito: {
      periodoReferencia: "2021-06 a 2026-06",
      totalComVitima: 23,
      totalSemVitima: 9,
      totalFatais: 6,
      veiculoMaisEnvolvido: "automovel",
      tiposViaCriticos: [
        "SP-300 km 566-570",
        "SP-568",
        "Vicinal Eugênio Salesse",
      ],
      horariosCriticos: [17, 18],
      diasCriticos: ["segunda"],
      observacao: "Acidentes associados ao fluxo no trevo de acesso à SP-568 e tráfego na Rondon.",
      fonte: "Infosiga-SP Painel de Sinistros (Bento de Abreu)",
      confianca: "oficial",
      fonteUrl: "file:///G:/Meu Drive/Arquivos Josemar/Projetos não vercionados/5 Cia/Roteiro de policiamento/sinistros/Painel_de_Sinistros bento de abreu.pdf",
    },
    frota: {
      total: 1769,
      automoveis: 992,
      motocicletas: 296,
      caminhoes: 59,
      percentualMotos: 0.1673,
      dataReferencia: "2026-05",
      fonte: "Senatran - Frota por Município (Maio/2026)",
      confianca: "oficial",
      fonteUrl: "file:///G:/Meu Drive/Arquivos Josemar/Projetos não vercionados/5 Cia/Roteiro de policiamento/Frota_por_municipio_e_tipo_Maio_2026.xlsx",
    },
    saude: [
      {
        nome: "UBS Dr. José Rosseto",
        tipo: "UBS",
        endereco: "Rua José Rosseto, 58 - Centro, Bento de Abreu - SP",
        telefone: "(18) 3601-1321",
        funciona24h: false,
        fonte: "CNES/DATASUS",
        lat: -21.27,
        lng: -50.8115,
      },
    ],
    instituicoesFinanceiras: [],
    ruralDetalhe: {
      totalPropriedades: 154,
      clustersAcesso: ["Vicinal Bento de Abreu a Lucélia"],
      producaoPrincipal: ["cana-de-açúcar", "pastagem"],
      alvosFurtoRural: ["defensivos agrícolas", "fios de cobre", "implementos"],
      fonte: "IBGE Censo Agro / CAR",
    },
    pontosAglomeracao: [],
    pontosEconomicos: [
      {
        nome: "Supermercado Frutos da Terra",
        tipo: "Supermercado",
        endereco: "Rua 27 de Março, 354, Centro, Bento de Abreu - SP",
        bairro: "Centro",
        lat: -21.2675,
        lng: -50.8122,
        fonte: "Prefeitura de Bento de Abreu",
        fonteUrl: "https://www.bentodeabreu.sp.gov.br",
      },
      {
        nome: "Novo N.F. Posto Bento de Abreu",
        tipo: "Posto",
        endereco: "Rua Ernesto Scatena, 35, Centro, Bento de Abreu - SP",
        bairro: "Centro",
        lat: -21.2682,
        lng: -50.8118,
        fonte: "ANP",
        fonteUrl: "https://www.gov.br/anp",
      },
    ],
    entidadesSociais: [
      {
        nome: "CRAS - Centro de Referência de Assistência Social de Bento de Abreu",
        tipo: "CRAS",
        endereco: "Rua Sampaio Vidal, 250, Centro, Bento de Abreu - SP",
        bairro: "Centro",
        lat: -21.2685,
        lng: -50.8128,
        publicoAlvo: "População sob vulnerabilidade social urbana e rural",
        relevanciaPrevencao: "Combate à vulnerabilidade e exclusão por meio de programas sociais contínuos",
        fonte: "Prefeitura Municipal de Bento de Abreu",
        fonteUrl: "https://www.bentodeabreu.sp.gov.br",
      },
    ],
    unidadesPrisionais: null,
    metadata: {
      versao: "3.3",
      dataLevantamento: "2026-06-16",
      responsavel: "Agente de Inteligência de Segurança Pública",
      fontes: [
        "Prefeitura Municipal de Bento de Abreu",
        "ANP (Postos)",
        "OpenStreetMap/Nominatim Geocoding",
      ],
      statusValidacao: "parcial",
      camposNaoEncontrados: [
        "DadosPPI.Bento de Abreu.perfilCriminal.violenciaDomestica",
        "DadosPPI.Bento de Abreu.perfilCriminal.perturbacaoSossego",
        "DadosPPI.Bento de Abreu.perfilCriminal.danoVandalismo",
        "DadosPPI.Bento de Abreu.perfilCriminal.embriaguezVolante",
      ],
    },
  },
};
