import type { DadosPPI } from "./types-ppi";
import type { Municipio } from "../types";

export const PPI_5CIA: Record<Municipio, DadosPPI> = {
  Guararapes: {
    aisp: ["AISP 1 (Setor Urbano)", "AISP 2 (Setor Rural / Ribeiro do Vale)"],
    hotspots: [
      {
        local: "Zona Comercial da Av. Rio Branco",
        endereco: "Av. Rio Branco, Centro, Guararapes - SP",
        bairro: "Centro",
        crimePrincipal: "Furto",
        periodosCriticos: ["manha", "tarde"],
        horaInicioCritico: null,
        horaFimCritico: null,
        diasCriticos: [],
        frequenciaAnual: null,
        modalidadesRecomendadas: ["POST", "PE"],
        risco: "Médio",
        fonte: "comando_5cia",
        confianca: "a_validar_comando",
      },
      {
        local: "Área Industrial - Entorno da Usina Unialco",
        endereco: "Estrada da Usina Unialco, Guararapes - SP",
        bairro: "Zona Rural",
        crimePrincipal: "Furto de fios e defensivos agrícolas",
        periodosCriticos: ["noite", "madrugada"],
        horaInicioCritico: null,
        horaFimCritico: null,
        diasCriticos: [],
        frequenciaAnual: null,
        modalidadesRecomendadas: ["RURAL"],
        risco: "Médio",
        fonte: "comando_5cia",
        confianca: "a_validar_comando",
      },
    ],
    escolas: [
      {
        nome: "EE Prof. Aimone Sala",
        endereco: "Av. Marechal Floriano, 905, Centro, Guararapes - SP",
        bairro: "Centro",
        tipo: "Estadual",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Estadual",
        etapas: ["Fundamental", "Medio"],
      },
      {
        nome: "EE João Arruda Brasil",
        endereco: "Rua Prudente de Morais, 951, Centro, Guararapes - SP",
        bairro: "Centro",
        tipo: "Estadual",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Estadual",
        etapas: ["Fundamental", "Medio", "EJA"],
      },
      {
        nome: "EE Prof. Waldemar Queiroz",
        endereco: "Rua Adelmo Caleffi, 120, Jardim Aeroporto, Guararapes - SP",
        bairro: "Jardim Aeroporto",
        tipo: "Estadual",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Estadual",
        etapas: ["Fundamental", "Medio"],
      },
      {
        nome: "EMEB Dr. Antonio Pinto de Oliveira",
        endereco: "Rua Aymorés, 350, Centro, Guararapes - SP",
        bairro: "Centro",
        tipo: "Municipal",
        turnoEntrada: null,
        turnoSaida: null,
        turnoEntradaTarde: null,
        turnoSaidaTarde: null,
        dependencia: "Municipal",
        etapas: ["Fundamental", "Pre-escola"],
      },
      {
        nome: "EMEB Professora Brigida Cagnin Zancaner",
        endereco:
          "Rua General Osório, 1420, Bairro Industrial, Guararapes - SP",
        bairro: "Bairro Industrial",
        tipo: "Municipal",
        turnoEntrada: null,
        turnoSaida: null,
        turnoEntradaTarde: null,
        turnoSaidaTarde: null,
        dependencia: "Municipal",
        etapas: ["Fundamental", "Pre-escola"],
      },
      {
        nome: "EMEB Professor Francisco de Almeida Ribeiro",
        endereco: "Rua Prudente de Morais, 137, Centro, Guararapes - SP",
        bairro: "Centro",
        tipo: "Municipal",
        turnoEntrada: null,
        turnoSaida: null,
        turnoEntradaTarde: null,
        turnoSaidaTarde: null,
        dependencia: "Municipal",
        etapas: ["Fundamental", "Pre-escola"],
      },
      {
        nome: "EMEB Professora Ivete Abdo Theodoro de Oliveira",
        endereco: "Rua Aymorés, 1500, Jardim Continental, Guararapes - SP",
        bairro: "Jardim Continental",
        tipo: "Municipal",
        turnoEntrada: null,
        turnoSaida: null,
        turnoEntradaTarde: null,
        turnoSaidaTarde: null,
        dependencia: "Municipal",
        etapas: ["Fundamental", "Pre-escola"],
      },
    ],
    infraestruturaCritica: {
      delegacia: {
        nome: "Delegacia de Polícia Civil de Guararapes",
        endereco: "Rua Prudente de Morais, 385, Centro, Guararapes - SP",
        telefone: "(18) 3606-4999",
      },
      upa: {
        nome: "Pronto Socorro - Santa Casa de Misericórdia de Guararapes",
        endereco: "Avenida Marechal Floriano, 1602, Centro, Guararapes - SP",
        telefone: "(18) 3406-9000",
      },
      bombeiros: null,
    },
    policiaComunitaria: {
      conseg: null,
      programas: ["PROERD (Programa Educacional de Resistência às Drogas)"],
    },
    transito: {
      periodoReferencia: "2025-06 a 2026-05",
      totalComVitima: 48,
      totalSemVitima: 92,
      totalFatais: 4,
      veiculoMaisEnvolvido: "motocicleta",
      tiposViaCriticos: ["SP-300 km 550-555", "Av. Rio Branco", "SP-473"],
      horariosCriticos: [17, 18, 19],
      diasCriticos: ["sexta", "sabado"],
      observacao:
        "Alta ocorrência de sinistros com motocicletas na Av. Rio Branco e colisões traseiras na SP-300.",
      fonte: "Infosiga-SP",
    },
    frota: {
      total: 25469,
      automoveis: 12436,
      motocicletas: 4947,
      caminhoes: 1080,
      percentualMotos: 0.194,
      dataReferencia: "2026-05",
      fonte: "Senatran",
    },
    saude: [
      {
        nome: "Pronto Socorro - Santa Casa de Misericórdia de Guararapes",
        tipo: "Hospital",
        endereco: "Avenida Marechal Floriano, 1602, Centro, Guararapes - SP",
        telefone: "(18) 3406-9000",
        funciona24h: true,
        fonte: "CNES/DATASUS",
      },
    ],
    instituicoesFinanceiras: [
      {
        tipo: "Agencia",
        nome: "Banco do Brasil - Agência Guararapes",
        banco: "Banco do Brasil",
        endereco:
          "Praça Nossa Senhora da Conceição, 308 - Centro, Guararapes - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
      },
      {
        tipo: "Agencia",
        nome: "Bradesco - Agência Guararapes",
        banco: "Bradesco",
        endereco: "Rua Marechal Deodoro, 1021 - Centro, Guararapes - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
      },
      {
        tipo: "Agencia",
        nome: "Caixa Econômica Federal - Agência Guararapes",
        banco: "Caixa",
        endereco: "Avenida Marechal Floriano, 675 - Centro, Guararapes - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
      },
      {
        tipo: "Loterica",
        nome: "Lotérica Guararapes",
        banco: "Caixa",
        endereco: "Rua Prudente de Morais, s/n - Centro, Guararapes - SP",
        alvoExplosaoCaixa: false,
        fonte: "Caixa",
      },
    ],
    ruralDetalhe: {
      totalPropriedades: 512,
      clustersAcesso: [
        "Estrada Vicinal GRP-010",
        "Estrada da Usina Unialco",
        "Estrada da Fazenda JBS",
      ],
      producaoPrincipal: ["cana-de-açúcar", "pasto/pecuária de corte"],
      alvosFurtoRural: [
        "defensivos agrícolas",
        "fios de cobre",
        "combustível",
        "implementos",
      ],
      fonte: "IBGE Censo Agro / CAR",
    },
    pontosAglomeracao: [
      {
        nome: "Feira Livre de Guararapes",
        tipo: "FeiraLivre",
        endereco: "Praça Nossa Senhora da Conceição, Centro, Guararapes - SP",
        diasHorarios: "Quarta e sábado 06:00-13:00",
        fonte: "Prefeitura de Guararapes",
      },
    ],
    unidadePrisional: null,
    metadata: {
      versao: "3.3",
      dataLevantamento: "2026-06-15",
      responsavel: "Agente de Inteligência de Segurança Pública",
      fontes: [
        "Censo 2022 IBGE",
        "Estatísticas da SSP-SP",
        "SEE-SP / INEP Portal da Educação",
        "Prefeitura Municipal de Guararapes",
        "Infosiga-SP",
        "Senatran",
        "CNES/DATASUS",
        "ESTBAN/BCB",
      ],
      statusValidacao: "parcial",
      camposNaoEncontrados: [
        "DadosPPI.Guararapes.policiaComunitaria.conseg",
        "DadosPPI.Guararapes.hotspots[0].horaInicioCritico",
        "DadosPPI.Guararapes.hotspots[0].horaFimCritico",
        "DadosPPI.Guararapes.hotspots[0].diasCriticos",
        "DadosPPI.Guararapes.hotspots[0].frequenciaAnual",
        "DadosPPI.Guararapes.hotspots[1].horaInicioCritico",
        "DadosPPI.Guararapes.hotspots[1].horaFimCritico",
        "DadosPPI.Guararapes.hotspots[1].diasCriticos",
        "DadosPPI.Guararapes.hotspots[1].frequenciaAnual",
        "DadosPPI.Guararapes.escolas[3].turnoEntrada",
        "DadosPPI.Guararapes.escolas[3].turnoSaida",
        "DadosPPI.Guararapes.escolas[3].turnoEntradaTarde",
        "DadosPPI.Guararapes.escolas[3].turnoSaidaTarde",
        "DadosPPI.Guararapes.escolas[4].turnoEntrada",
        "DadosPPI.Guararapes.escolas[4].turnoSaida",
        "DadosPPI.Guararapes.escolas[4].turnoEntradaTarde",
        "DadosPPI.Guararapes.escolas[4].turnoSaidaTarde",
        "DadosPPI.Guararapes.escolas[5].turnoEntrada",
        "DadosPPI.Guararapes.escolas[5].turnoSaida",
        "DadosPPI.Guararapes.escolas[5].turnoEntradaTarde",
        "DadosPPI.Guararapes.escolas[5].turnoSaidaTarde",
        "DadosPPI.Guararapes.escolas[6].turnoEntrada",
        "DadosPPI.Guararapes.escolas[6].turnoSaida",
        "DadosPPI.Guararapes.escolas[6].turnoEntradaTarde",
        "DadosPPI.Guararapes.escolas[6].turnoSaidaTarde",
      ],
    },
  },
  Valparaíso: {
    aisp: [
      "AISP I (Setor Rural Norte)",
      "AISP II (Setor Rural Oeste)",
      "AISP III (Setor Rural Sul)",
      "AISP IV (Setor Urbano / Comercial)",
    ],
    hotspots: [
      {
        local: "Zona Comercial da Av. Nove de Julho",
        endereco: "Av. Nove de Julho, Centro, Valparaíso - SP",
        bairro: "Centro",
        crimePrincipal: "Furto",
        periodosCriticos: ["manha", "tarde"],
        horaInicioCritico: null,
        horaFimCritico: null,
        diasCriticos: [],
        frequenciaAnual: null,
        modalidadesRecomendadas: ["POST", "PE"],
        risco: "Médio",
        fonte: "comando_5cia",
        confianca: "a_validar_comando",
      },
    ],
    escolas: [
      {
        nome: "EE Vicente Barbosa",
        endereco: "Rua Agostinho Barbosa, 335, Centro, Valparaíso - SP",
        bairro: "Centro",
        tipo: "Estadual",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Estadual",
        etapas: ["Fundamental", "Medio"],
      },
      {
        nome: "EE Prof. David Golias",
        endereco:
          "Rua Gaspar Vaz, 700, Conj. Hab. Miguel Villar, Valparaíso - SP",
        bairro: "Conj. Hab. Miguel Villar",
        tipo: "Estadual",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Estadual",
        etapas: ["Fundamental", "Medio"],
      },
      {
        nome: "EMEF Prof. Persio Scatena Garcia",
        endereco: "Rua Bartolomeu Bueno, 878, Centro, Valparaíso - SP",
        bairro: "Centro",
        tipo: "Municipal",
        turnoEntrada: null,
        turnoSaida: null,
        turnoEntradaTarde: null,
        turnoSaidaTarde: null,
        dependencia: "Municipal",
        etapas: ["Fundamental"],
      },
      {
        nome: "EMEF José de Castro",
        endereco: "Rua Eduardo Geralde, 289, Centro, Valparaíso - SP",
        bairro: "Centro",
        tipo: "Municipal",
        turnoEntrada: null,
        turnoSaida: null,
        turnoEntradaTarde: null,
        turnoSaidaTarde: null,
        dependencia: "Municipal",
        etapas: ["Fundamental"],
      },
      {
        nome: "EMEF Djanira dos Santos Benetti",
        endereco: "Rua Eurípides Leite Bastos, 116, Valparaíso - SP",
        bairro: "[DADO_NÃO_ENCONTRADO]",
        tipo: "Municipal",
        turnoEntrada: null,
        turnoSaida: null,
        turnoEntradaTarde: null,
        turnoSaidaTarde: null,
        dependencia: "Municipal",
        etapas: ["Fundamental"],
      },
    ],
    infraestruturaCritica: {
      delegacia: {
        nome: "Delegacia de Polícia Civil de Valparaíso",
        endereco: "Rua Juca de Castro, 297, Valparaíso - SP",
        telefone: "(18) 3401-1246",
      },
      upa: {
        nome: "Santa Casa de Misericórdia de Valparaíso",
        endereco: "Rua Bartolomeu Bueno, 241, Centro, Valparaíso - SP",
        telefone: "(18) 3401-7171",
      },
      bombeiros: null,
    },
    policiaComunitaria: {
      conseg: null,
      programas: ["PROERD", "Policiamento Escolar", "Patrulha Maria da Penha"],
    },
    transito: {
      periodoReferencia: "2025-06 a 2026-05",
      totalComVitima: 35,
      totalSemVitima: 68,
      totalFatais: 3,
      veiculoMaisEnvolvido: "automovel",
      tiposViaCriticos: [
        "SP-300 km 573-578",
        "Av. Nove de Julho",
        "Vicinal Eugênio Salesse",
      ],
      horariosCriticos: [18, 19, 20],
      diasCriticos: ["sexta", "sabado"],
      observacao:
        "Foco de colisões e atropelamentos no trecho urbano da SP-300 no final da tarde.",
      fonte: "Infosiga-SP",
    },
    frota: {
      total: 18250,
      automoveis: 8940,
      motocicletas: 3810,
      caminhoes: 820,
      percentualMotos: 0.208,
      dataReferencia: "2026-05",
      fonte: "Senatran",
    },
    saude: [
      {
        nome: "Santa Casa de Misericórdia de Valparaíso",
        tipo: "SantaCasa",
        endereco: "Rua Bartolomeu Bueno, 241, Centro, Valparaíso - SP",
        telefone: "(18) 3401-7171",
        funciona24h: true,
        fonte: "CNES/DATASUS",
      },
    ],
    instituicoesFinanceiras: [
      {
        tipo: "Agencia",
        nome: "Banco do Brasil - Agência Valparaíso",
        banco: "Banco do Brasil",
        endereco: "Rua Quinze de Novembro, 70 - Centro, Valparaíso - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
      },
      {
        tipo: "Agencia",
        nome: "Bradesco - Agência Valparaíso",
        banco: "Bradesco",
        endereco: "Rua Quinze de Novembro, 41 - Centro, Valparaíso - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
      },
      {
        tipo: "Agencia",
        nome: "Santander - Agência Valparaíso",
        banco: "Santander",
        endereco: "Avenida Nove de Julho, 580 - Centro, Valparaíso - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
      },
      {
        tipo: "Agencia",
        nome: "Caixa Econômica Federal - Agência Valparaíso",
        banco: "Caixa",
        endereco: "Rua Quinze de Novembro, s/n - Centro, Valparaíso - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
      },
      {
        tipo: "Loterica",
        nome: "Lotérica Valparaíso",
        banco: "Caixa",
        endereco: "Rua Quinze de Novembro, Centro, Valparaíso - SP",
        alvoExplosaoCaixa: false,
        fonte: "Caixa",
      },
    ],
    ruralDetalhe: {
      totalPropriedades: 398,
      clustersAcesso: ["Estrada da Usina da Mata", "Vicinais de ligação rural"],
      producaoPrincipal: ["cana-de-açúcar", "pasto"],
      alvosFurtoRural: ["defensivos agrícolas", "fios de cobre", "combustível"],
      fonte: "IBGE Censo Agro / CAR",
    },
    pontosAglomeracao: [
      {
        nome: "Terminal Rodoviário de Valparaíso",
        tipo: "Terminal",
        endereco: "Avenida Nove de Julho, Centro, Valparaíso - SP",
        diasHorarios: "Diário 24h",
        fonte: "Prefeitura de Valparaíso",
      },
    ],
    unidadePrisional: {
      nome: "Centro de Progressão Penitenciária de Valparaíso (CPP)",
      tipo: "Presídio Semiaberto",
      endereco:
        "Estrada Municipal VPS 012/VPS 351, Km 02 - Bairro Valdevino Souza Pacheco, Valparaíso/SP",
    },
    metadata: {
      versao: "3.3",
      dataLevantamento: "2026-06-15",
      responsavel: "Agente de Inteligência de Segurança Pública",
      fontes: [
        "Censo 2022 IBGE",
        "Estatísticas da SSP-SP",
        "Portal QEdu",
        "SEE-SP",
        "Infosiga-SP",
        "Senatran",
        "CNES/DATASUS",
        "ESTBAN/BCB",
      ],
      statusValidacao: "parcial",
      camposNaoEncontrados: [
        "DadosPPI.Valparaíso.policiaComunitaria.conseg",
        "DadosPPI.Valparaíso.hotspots[0].horaInicioCritico",
        "DadosPPI.Valparaíso.hotspots[0].horaFimCritico",
        "DadosPPI.Valparaíso.hotspots[0].diasCriticos",
        "DadosPPI.Valparaíso.hotspots[0].frequenciaAnual",
        "DadosPPI.Valparaíso.escolas[4].bairro",
        "DadosPPI.Valparaíso.escolas[2].turnoEntrada",
        "DadosPPI.Valparaíso.escolas[2].turnoSaida",
        "DadosPPI.Valparaíso.escolas[2].turnoEntradaTarde",
        "DadosPPI.Valparaíso.escolas[2].turnoSaidaTarde",
        "DadosPPI.Valparaíso.escolas[3].turnoEntrada",
        "DadosPPI.Valparaíso.escolas[3].turnoSaida",
        "DadosPPI.Valparaíso.escolas[3].turnoEntradaTarde",
        "DadosPPI.Valparaíso.escolas[3].turnoSaidaTarde",
        "DadosPPI.Valparaíso.escolas[4].turnoEntrada",
        "DadosPPI.Valparaíso.escolas[4].turnoSaida",
        "DadosPPI.Valparaíso.escolas[4].turnoEntradaTarde",
        "DadosPPI.Valparaíso.escolas[4].turnoSaidaTarde",
      ],
    },
  },
  Rubiácea: {
    aisp: ["AISP 1 (Município de Rubiácea)"],
    hotspots: [
      {
        local: "Trevo de Acesso à SP-300 / Praça de Pedágio",
        endereco: "SP-300 Rodovia Marechal Rondon, km 562, Rubiácea - SP",
        bairro: "Zona Rural",
        crimePrincipal: "Evasão de divisas / Roubo / Furto de carga",
        periodosCriticos: ["noite", "madrugada"],
        horaInicioCritico: null,
        horaFimCritico: null,
        diasCriticos: [],
        frequenciaAnual: null,
        modalidadesRecomendadas: ["FISC"],
        risco: "Baixo",
        fonte: "comando_5cia",
        confianca: "a_validar_comando",
      },
    ],
    escolas: [
      {
        nome: "EE Coronel Francisco Prudente Correa",
        endereco:
          "Rua Dona Angelina de Lima Correa, 168, Centro, Rubiácea - SP",
        bairro: "Centro",
        tipo: "Estadual",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Estadual",
        etapas: ["Fundamental", "Medio", "EJA"],
      },
      {
        nome: "EMEF Professor Luciano Tavares de Moraes",
        endereco: "Rua Ozório Brasileiro da Silva, 25, Centro, Rubiácea - SP",
        bairro: "Centro",
        tipo: "Municipal",
        turnoEntrada: null,
        turnoSaida: null,
        turnoEntradaTarde: null,
        turnoSaidaTarde: null,
        dependencia: "Municipal",
        etapas: ["Fundamental"],
      },
      {
        nome: "EMEF Renato de Freitas",
        endereco: "Rua São João, 185, Caramuru, Rubiácea - SP",
        bairro: "Zona Rural",
        tipo: "Municipal",
        turnoEntrada: null,
        turnoSaida: null,
        turnoEntradaTarde: null,
        turnoSaidaTarde: null,
        dependencia: "Municipal",
        etapas: ["Fundamental"],
      },
    ],
    infraestruturaCritica: {
      delegacia: {
        nome: "Delegacia de Polícia Civil de Rubiácea",
        endereco:
          "Rua Cel. Francisco Prudente Corrêa, 445, Centro, Rubiácea - SP",
        telefone: "(18) 3697-1119",
      },
      upa: {
        nome: "UBS III de Rubiácea",
        endereco:
          "Rua Francisco de Paula Leite Nogueira, 208, Centro, Rubiácea - SP",
        telefone: "(18) 3697-1128",
      },
      bombeiros: null,
    },
    policiaComunitaria: {
      conseg: null,
      programas: ["Ronda Rural", "PROERD"],
    },
    transito: {
      periodoReferencia: "2025-06 a 2026-05",
      totalComVitima: 6,
      totalSemVitima: 14,
      totalFatais: 1,
      veiculoMaisEnvolvido: "automovel",
      tiposViaCriticos: ["SP-300 km 560-564", "Vicinal Geraldo Stringhetta"],
      horariosCriticos: [7, 18],
      diasCriticos: ["domingo"],
      observacao:
        "Sinistros concentrados na praça de pedágio e na vicinal de acesso ao bairro Caramuru.",
      fonte: "Infosiga-SP",
    },
    frota: {
      total: 2100,
      automoveis: 1050,
      motocicletas: 420,
      caminhoes: 90,
      percentualMotos: 0.2,
      dataReferencia: "2026-05",
      fonte: "Senatran",
    },
    saude: [
      {
        nome: "UBS III de Rubiácea",
        tipo: "UBS",
        endereco:
          "Rua Francisco de Paula Leite Nogueira, 208 - Centro, Rubiácea - SP",
        telefone: "(18) 3697-1128",
        funciona24h: false,
        fonte: "CNES/DATASUS",
      },
    ],
    instituicoesFinanceiras: [
      {
        tipo: "Agencia",
        nome: "Banco do Brasil - Agência Rubiácea",
        banco: "Banco do Brasil",
        endereco: "Avenida Min. Konder, 107 - Centro, Rubiácea - SP",
        alvoExplosaoCaixa: true,
        fonte: "ESTBAN/BCB",
      },
    ],
    ruralDetalhe: {
      totalPropriedades: 185,
      clustersAcesso: ["Vicinal Geraldo Stringhetta (Rubiácea a Caramuru)"],
      producaoPrincipal: ["cana-de-açúcar", "pasto"],
      alvosFurtoRural: ["defensivos agrícolas", "fios de cobre", "combustível"],
      fonte: "IBGE Censo Agro / CAR",
    },
    pontosAglomeracao: [],
    unidadePrisional: null,
    metadata: {
      versao: "3.3",
      dataLevantamento: "2026-06-15",
      responsavel: "Agente de Inteligência de Segurança Pública",
      fontes: [
        "Censo 2022 IBGE",
        "Estatísticas da SSP-SP",
        "Prefeitura de Rubiácea",
        "SEE-SP",
        "Infosiga-SP",
        "Senatran",
        "CNES/DATASUS",
        "ESTBAN/BCB",
      ],
      statusValidacao: "parcial",
      camposNaoEncontrados: [
        "DadosPPI.Rubiácea.policiaComunitaria.conseg",
        "DadosPPI.Rubiácea.hotspots[0].horaInicioCritico",
        "DadosPPI.Rubiácea.hotspots[0].horaFimCritico",
        "DadosPPI.Rubiácea.hotspots[0].diasCriticos",
        "DadosPPI.Rubiácea.hotspots[0].frequenciaAnual",
        "DadosPPI.Rubiácea.escolas[1].turnoEntrada",
        "DadosPPI.Rubiácea.escolas[1].turnoSaida",
        "DadosPPI.Rubiácea.escolas[1].turnoEntradaTarde",
        "DadosPPI.Rubiácea.escolas[1].turnoSaidaTarde",
        "DadosPPI.Rubiácea.escolas[2].turnoEntrada",
        "DadosPPI.Rubiácea.escolas[2].turnoSaida",
        "DadosPPI.Rubiácea.escolas[2].turnoEntradaTarde",
        "DadosPPI.Rubiácea.escolas[2].turnoSaidaTarde",
      ],
    },
  },
  "Bento de Abreu": {
    aisp: ["AISP 1 (Município de Bento de Abreu)"],
    hotspots: [
      {
        local: "Trevo de Bento de Abreu (SP-300 / SP-568)",
        endereco: "Trevo de Bento de Abreu, Bento de Abreu - SP",
        bairro: "Zona Rural",
        crimePrincipal: "Tráfico de drogas / Furto de veículos",
        periodosCriticos: ["noite", "madrugada"],
        horaInicioCritico: null,
        horaFimCritico: null,
        diasCriticos: [],
        frequenciaAnual: null,
        modalidadesRecomendadas: ["FISC"],
        risco: "Baixo",
        fonte: "comando_5cia",
        confianca: "a_validar_comando",
      },
    ],
    escolas: [
      {
        nome: "EE Prof. Olímpio Camargo",
        endereco: "Rua 27 de Março, 640, Centro, Bento de Abreu - SP",
        bairro: "Centro",
        tipo: "Estadual",
        turnoEntrada: "07:00",
        turnoSaida: "12:20",
        turnoEntradaTarde: "13:00",
        turnoSaidaTarde: "18:20",
        dependencia: "Estadual",
        etapas: ["Fundamental", "Medio", "EJA"],
      },
      {
        nome: "EMEF Prof. Dorival Reis Camargo Barrionuevo Sanchez",
        endereco: "Rua Hugo Scatena, 687, Centro, Bento de Abreu - SP",
        bairro: "Centro",
        tipo: "Municipal",
        turnoEntrada: null,
        turnoSaida: null,
        turnoEntradaTarde: null,
        turnoSaidaTarde: null,
        dependencia: "Municipal",
        etapas: ["Fundamental"],
      },
    ],
    infraestruturaCritica: {
      delegacia: {
        nome: "Delegacia de Polícia Civil de Bento de Abreu",
        endereco:
          "Rua João Belmiro de Brito, s/nº, Centro, Bento de Abreu - SP",
        telefone: "(18) 3601-1221",
      },
      upa: {
        nome: "UBS Dr. José Rosseto",
        endereco: "Rua José Rosseto, 58, Centro, Bento de Abreu - SP",
        telefone: "(18) 3601-1321",
      },
      bombeiros: null,
    },
    policiaComunitaria: {
      conseg: null,
      programas: ["Ronda Rural", "PROERD"],
    },
    transito: {
      periodoReferencia: "2025-06 a 2026-05",
      totalComVitima: 4,
      totalSemVitima: 10,
      totalFatais: 0,
      veiculoMaisEnvolvido: "automovel",
      tiposViaCriticos: [
        "SP-300 km 566-570",
        "SP-568",
        "Vicinal Eugênio Salesse",
      ],
      horariosCriticos: [17, 18],
      diasCriticos: ["segunda"],
      observacao:
        "Acidentes associados ao fluxo no trevo de acesso à SP-568 e tráfego na Rondon.",
      fonte: "Infosiga-SP",
    },
    frota: {
      total: 1950,
      automoveis: 980,
      motocicletas: 370,
      caminhoes: 80,
      percentualMotos: 0.19,
      dataReferencia: "2026-05",
      fonte: "Senatran",
    },
    saude: [
      {
        nome: "UBS Dr. José Rosseto",
        tipo: "UBS",
        endereco: "Rua José Rosseto, 58 - Centro, Bento de Abreu - SP",
        telefone: "(18) 3601-1321",
        funciona24h: false,
        fonte: "CNES/DATASUS",
      },
    ],
    instituicoesFinanceiras: [], // Bento de Abreu não possui agências nem lotéricas
    ruralDetalhe: {
      totalPropriedades: 154,
      clustersAcesso: ["Vicinal Bento de Abreu a Lucélia"],
      producaoPrincipal: ["cana-de-açúcar", "pastagem"],
      alvosFurtoRural: ["defensivos agrícolas", "fios de cobre", "implementos"],
      fonte: "IBGE Censo Agro / CAR",
    },
    pontosAglomeracao: [],
    unidadePrisional: null,
    metadata: {
      versao: "3.3",
      dataLevantamento: "2026-06-15",
      responsavel: "Agente de Inteligência de Segurança Pública",
      fontes: [
        "Censo 2022 IBGE",
        "Estatísticas da SSP-SP",
        "Prefeitura de Bento de Abreu",
        "SEE-SP",
        "Infosiga-SP",
        "Senatran",
        "CNES/DATASUS",
      ],
      statusValidacao: "parcial",
      camposNaoEncontrados: [
        "DadosPPI.Bento de Abreu.policiaComunitaria.conseg",
        "DadosPPI.Bento de Abreu.hotspots[0].horaInicioCritico",
        "DadosPPI.Bento de Abreu.hotspots[0].horaFimCritico",
        "DadosPPI.Bento de Abreu.hotspots[0].diasCriticos",
        "DadosPPI.Bento de Abreu.hotspots[0].frequenciaAnual",
        "DadosPPI.Bento de Abreu.escolas[1].turnoEntrada",
        "DadosPPI.Bento de Abreu.escolas[1].turnoSaida",
        "DadosPPI.Bento de Abreu.escolas[1].turnoEntradaTarde",
        "DadosPPI.Bento de Abreu.escolas[1].turnoSaidaTarde",
      ],
    },
  },
};
